### ISSUE TITLE
i3 and context menus

### ISSUE THREAD

**Issue by jeremejevs** [naelstrof/slop#103]
Whenever I trigger `maim` while there's a context menu open, `slop` terminates with this:

```
Couldn't grab the mouse after 10 tries.
```

Using this command to reproduce (open a menu while it sleeps):

```bash
sleep 3; maim -s /tmp/test.png
```

Works fine if there's no menu.

Slop 7.4
Maim 5.5
i3 4.15
Up-to-date Arch

**Edit**

[I guess it's a won't-fix](https://mail.gnome.org/archives/gtk-devel-list/2010-June/msg00154.html) (the problem dates back to [2002](https://bugzilla.gnome.org/show_bug.cgi?id=100903)...), at least on Slop's side. Maybe Maim could do something like what ShareX does on Windows, where it rasterizes the whole screen first, and then lets you select a region on it, but without any outlines for context menus.

**Comment by naelstrof** [comment]
Yeah I guess I could save all the window positions and save a static image to display and then wait until the keyboard/mouse is no longer grabbed. That's quite a bit of work though. I think wayland finally opened the ability to screenshot other windows, so I think any efforts I'll be putting into maim/slop would be making sure they work on wayland.

You can assume this issue is a WONTFIX for now. Sorry!

**Comment by jeremejevs** [comment]
No worries! Sway 1.0 is around the corner :slightly_smiling_face: I'm leaving i3/X as soon as it hits beta.

Thanks for making these utilities, they're very handy.
