### ISSUE TITLE
inconsistent size between clicking(without holding) on edges, corners, and anywhere else.

### ISSUE THREAD

**Issue by noah1786** [naelstrof/slop#110]
at non-borders or corners, it reports 0x0, at any corners it reports 1x1, at the left and right borders it reports 1x0, and at the up and down borders it reports 0x1.

I am running Gentoo Linux, slop v7.4

**Comment by naelstrof** [comment]
Could I get some visual examples? I know I'm doing some weird offsets in order to make sure you can select your whole screen regardless if you select the bottom-left corner to the upper-right or vise-versa.

I do the offsets here if you want to check it out yourself: https://github.com/naelstrof/slop/blob/master/src/slopstates.cpp#L100

**Comment by noah1786** [comment]
The attatched gif is a demonstration of the size issue. The outputs in rightmost terminal are given from 'slop -t 0' in a loop.
![output](https://user-images.githubusercontent.com/5668314/44592218-f48e6480-a78d-11e8-8270-ae18fe9099bc.gif)

**Comment by naelstrof** [comment]
Oh nice, yup that's a bug. What command are you using?

**Comment by noah1786** [comment]
for the slop output? 'slop -t 0'  for each.

**Comment by lucianposton** [comment]
@naelstrof what's the expected behavior for clicking? 1x1?
