### ISSUE TITLE
transparency in shader

### ISSUE THREAD

**Issue by TitouanT** [naelstrof/slop#138]
I have an issue with the transparency in shaders.
I don't know if the issue commes from slop or picom.

For example in crosshair.frag, setting `color.a = 0` right before `gl_FragColor = color` should make everything invisible.
And I get that: 
![image](https://user-images.githubusercontent.com/16353124/95883734-8e089e00-0d7b-11eb-8212-ab525adae617.png).

I have also noticed that the white is always fully opaque, no matter the value of component a.

**Comment by naelstrof** [comment]
I don't believe slop supports alpha at all. I think that highly depends on window manager and desktop environment.

So instead what slop does is supply the underlying desktop as a texture named "desktop" which you can sample and blend yourself.

**Comment by TitouanT** [comment]
Well, we do see my desktop underneath the loop and it is the live one, it's not from the still desktop texture.

So there is a bit of transparency but it doesn't work for every color.

It looks to me that when the opacity of a color is proportional to its magnitude.

**Comment by TitouanT** [comment]
In my example above I think we shouldn't be able to see the loop at all. We should see my desktop unchanged. Don't you agree ?

**Comment by naelstrof** [comment]
I double checked all my code, and I'm definitely blending alpha properly as far as I can tell. (I also clear the screen with transparency before drawing).

Here's where I enable alpha blending:
https://github.com/naelstrof/slop/blob/4b68db37ee932cd38815db64d125033d92df4763/src/slop.cpp#L273

So my guess is that the Window manager isn't blending it correctly, this might be my fault, there could be some hint I'm supposed to set, but finding documentation for that is extremely difficult and prone to being specific to the window manager you're using.

Luckily I can think of a couple other solutions. Solution 1 would probably be to simply `discard` any pixels you don't want to draw.

Solution 2 would be to manually blend with the "desktop" texture, which represents a snapshot of the desktop when slop started. This would guarantee that your shader will appear transparent, but comes with the limitation that it doesn't update real-time.

Slop by design doesn't update this texture because it would be expensive to do so-- however if you made a tiny edit it would contain a real-time texture of the desktop-- though this might cause a feedback loop since slop renders to it also. (You'd just have to remove this line: https://github.com/naelstrof/slop/blob/4b68db37ee932cd38815db64d125033d92df4763/src/framebuffer.cpp#L56)

**Comment by TitouanT** [comment]
Thanks for your reply it really helped me. I looked at the code in `slop.cpp` and I think I might have found the issue, I have issued a pull request with a possible fix. I was happy to find the fix there because the loop on the shaders above is difficult to make sense of ; you bind one framebuffer, draw on the other, bind the other and draw on the one. It must be right since you called one `pingpong` ^^

I also tried your quick hack to enable the live desktop texture but you were right there is a feedback loop.
And it's making everything laggy but that might be fixable by removing sleeping since updating the texture already takes time.
An option to update the desktop texture periodically would be extremely useful but we would need to clear slop's window first to prevent the feedback loop. I don't know how X11 works but would it be possible to access the pixel values directly ? (Instead of making a copy).

When testing stuff I found out that slop either do a core dumped or an out of memory from open gl after 3'30'' of execution every time. I don't know how one would go about fixing memory leak from open gl.
Maybe I should open another issue for that.

**Comment by naelstrof** [comment]
Oh nice, I'll take a look. As for the live texture thing, the leak comes from creating a new texture every frame. To fix it you'd simply need to reuse a texture rather than recreate it.

**Comment by TitouanT** [comment]
The leak was already there, but I understand why it has not been detected, slop rarely stays open for more than a few seconds. 3'30'' with no mouse clicking is painful to test ^^

**Comment by TitouanT** [comment]
The last shader was drawn twice, the first time bounded and the second time unbounded. I removed the first.
