### ISSUE TITLE
Unused #include <execinfo.h> in main.cpp

### ISSUE THREAD

**Issue by pullmoll** [naelstrof/slop#28]
It seems that no functions defined in `execinfo.h` are used in `src/main.cpp`.

Since e.g. `musl libc` does not have `execinfo.h` and no `backtrace()` etc. functions, it would be nice if the include and any (future) use of functions defined in `execinfo.h` could be guarded by an `#if defined(__GLIBC__)`.

For the 4.2.17 release the following would be sufficient in `src/main.cpp`:
```C
#if defined(__GLIBC__)
#include <execinfo.h>
#endif
```

**Comment by naelstrof** [comment]
Sorry about that! I was trying to figure out why slop was throwing random exceptions, and I wanted a trace for it since I'm dumb and don't use a debugger.
I ended up including that file and forgetting about it, despite never using it.
It's been fixed with 43b179df21d35b971f7d08634be4dd5da88dc2ed, thanks for the info!
