### ISSUE TITLE
Magnification and Highlight option conflict

### ISSUE THREAD

**Issue by ShadowKyogre** [naelstrof/slop#35]
More specifically, when magnification is turned on, there's no highlighting.

Screencast demonstrating this: https://youtu.be/Jzk9y0GUtso

Let me know if I need to test with other WMs too. This test was done with Compiz.

**Comment by naelstrof** [comment]
Heh I was wondering when someone would find that out, it's completely unimplemented. I'll get around to it.

**Comment by naelstrof** [comment]
Sorry about that, it should be fixed with: https://github.com/naelstrof/slop/commit/e063690c8d72d72fe7c081d4eb20021882ae8e6c

Tell me if it doesn't work as you intended, for example border values are discarded (despite perhaps being useful), and using a theme with highlight only uses the first corner image, but still requires all the images anyway.

**Comment by ShadowKyogre** [comment]
Tested it with the new commit and the highlighting is restored with the 
magnification on!
