### ISSUE TITLE
Slop magnifier windows moves out of sight

### ISSUE THREAD

**Issue by juriy-zn** [naelstrof/slop#36]
So I haven't looked at the code yet, thought I post it here first. 

I use slop (one of the ways at least) as my magnifier to see tiny text and such, but the window it shows zoomed stuff in is moving around all the time following my cursor, which I assume is normal, the problem is sometimes in its travelings the window gets out of my screen area, which happens when my cursor is at corners or sides of the area. 

Setup: 
i3wm (no patches), 
2 monitors: total resolution is 4480 x 1440, 1080p is to the left of 1440p and their bottoms are lined up, so 1440p is 360 pixels above 1080p, their geometries (from xrandr): 1080p - 1920x1080+0+360, 1440p - 2560x1440+1920+0,
command I use:
slop --nokeyboard --opengl -c 0,0,0,0 --min=1 --max=1 --magnify --magstrength=4 --magpixels=128,
where [4] and [128] can be anything, issue occurs at multiple inputs and does not consistently occur for the same input.

**Comment by naelstrof** [comment]
The relevant code you're looking for is here: https://github.com/naelstrof/slop/blob/master/src/glselectrectangle.cpp#L178

It does push the magnifying glass into the monitor to be visible, but it takes lower priority over keeping the magnifying glass outside the shot and away from the cursor (To prevent magnifying itself, and/or showing up in a screenshot).

It's not very intelligent, it just uses the *pushIn* and *pushOut* methods to push the magnifying glass in and out of rectangles. Which easily causes problems when approaching corners of the screen.

A cheesy fix would be to make it so that the *pushIn* command happens last, or the pushOut commands don't happen at all.

A good fix would be for pushOut to detect if it would be pushing it outside any monitors and to choose a different *ang* if so, while also being aware of the forbidden areas (the cursor/shot area).

I'll work on it when I can, but feel free to make the changes yourself if you want it done now.

**Comment by naelstrof** [comment]
No longer an issue.
