### ISSUE TITLE
Add back old shaders

### ISSUE THREAD

**Issue by notantonia** [naelstrof/slop#72]
There were some old shaders like refract, invert and hippie which I quite liked. They've stopped working now. I would attempt to rewrite them but it doesn't seem to be working.

The best I've managed is the following for `hippie.frag` (where `hippie.vert` is the same as the provided `blur1.vert` in shaderexamples)

```
#version 120

uniform sampler2D texture;
uniform sampler2D desktop;
uniform vec2 screenSize;
uniform float time;

varying vec2 uvCoord;

const float pi = 3.14159265f;

vec3 color(float x) {
    return max(min(sin(vec3(x,x+pi*2.0/3.0,x+pi*4.0/3.0))+0.5,1.0),0.0);
}

void main() {
    vec2 pos = (( gl_FragCoord.xy / screenSize.xy )-0.5)*screenSize.xy/screenSize.x*4.0;
    pos+=normalize(pos);
    pos.xy+=sin(pos.yx*10.0)*0.1;
    float r=(2.0/(dot(pos,pos)*10.0+1.0));
    vec2 rr=vec2(cos(r),sin(r));
    pos=pos.xy*rr.xx+pos.yx*rr.yy*vec2(-1.0,1.0);
    float f=(length(pos)*10.0)+time;
    f+=sin(atan(pos.y,pos.x)*7.0)*5.0;
    float alpha = texture2D(texture,uvCoord).a;
    vec4 c = vec4(color(f), alpha);
    gl_FragColor = vec4(color(f), alpha);
}
```

(which is the same as the previous version except resolution is replaced with screenSize, and all the desktop* variables removed)

However, this doesn't give the same effect as before. Notably, the colours aren't as visible, and the selection rectangle is also coloured (where before it wasn't).

I attempted setting `alpha` to `1.0` to fix the colour visibility issue, but I am getting `OpenGL threw an error: INVALID_VALUE`. This is actually the same error I get when I attempt a simple shader like so:

```
#version 120

void main {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
```

**Comment by naelstrof** [comment]
`uniform sampler2D texture;` is actually a required uniform, as is `position`, and `uv`.

I didn't include hippie because I didn't actually create that shader, I stole it from the Shader Toy website.
I don't mind including it now since it's not actually part of the software.

As for the refract I just didn't realize you can't get the same effect from chaining up what I've included.

I'll take a look at it when I can.

**Comment by naelstrof** [comment]
There's something definitely goofy about the shader chaining, it was seemingly ignoring my alpha inputs. Though I think I'm just confused since I got it working without changing any of the rendering code.

I re-added hippie, refract, and invert. You can find them here:
https://github.com/naelstrof/slop/tree/master/shaderexamples

Remember you can chain them up now, so `slop -r invert,refract,wiggle -b 100 -c 1,1,1,1` looks pretty cool.
