### ISSUE TITLE
Make is failing at 6% with EGL/egl.h missing

### ISSUE THREAD

**Issue by pixelastic** [naelstrof/slop#88]
Hello,

I'm trying to install slop on Ubuntu 16.04. I think I have all the dependencies needed (the one listed in the readme, as well as the one listed in #52), but I end up with the following error:

```
$ make
[  6%] Building CXX object CMakeFiles/slopy.dir/src/slop.cpp.o
In file included from /home/tim/local/src/slop/src/framebuffer.hpp:29:0,
                 from /home/tim/local/src/slop/src/window.hpp:40,
                 from /home/tim/local/src/slop/src/slop.cpp:19:
/home/tim/local/src/slop/src/shader.hpp:32:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.
CMakeFiles/slopy.dir/build.make:182: recipe for target 'CMakeFiles/slopy.dir/src/slop.cpp.o' failed
make[2]: *** [CMakeFiles/slopy.dir/src/slop.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/slopy.dir/all' failed
make[1]: *** [CMakeFiles/slopy.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I've previously ran `cmake -DCMAKE_INSTALL_PREFIX="/usr" ./` that got me the following output:
```
CMake Warning at CMakeLists.txt:112 (find_package):
  By not providing "FindICU.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ICU", but
  CMake did not find one.

  Could not find a package configuration file provided by "ICU" with any of
  the following names:

    ICUConfig.cmake
    icu-config.cmake

  Add the installation prefix of "ICU" to CMAKE_PREFIX_PATH or set "ICU_DIR"
  to a directory containing one of the above files.  If "ICU" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/tim/local/src/slop
```

I'm a bit confused about the ICU files things. I don't really understand how to fix it, nor if it's related at all.

Any help appreciated,

Thanks

**Comment by naelstrof** [comment]
Seems like you need EGL installed. Make sure you have the latest version of
slop too. If you tell me which Linux distro you're using I could be more
specific.

On Oct 24, 2017 10:14 AM, <notifications@github.com> wrote:

Hello,

I'm trying to install slop on Ubuntu 16.04. I think I have all the
dependencies needed (the one listed in the readme, as well as the one
listed in #52 <https://github.com/naelstrof/slop/issues/52>), but I end up
with the following error:

$ make
[  6%] Building CXX object CMakeFiles/slopy.dir/src/slop.cpp.o
In file included from /home/tim/local/src/slop/src/framebuffer.hpp:29:0,
                 from /home/tim/local/src/slop/src/window.hpp:40,
                 from /home/tim/local/src/slop/src/slop.cpp:19:
/home/tim/local/src/slop/src/shader.hpp:32:21: fatal error: EGL/egl.h:
No such file or directory
compilation terminated.
CMakeFiles/slopy.dir/build.make:182: recipe for target
'CMakeFiles/slopy.dir/src/slop.cpp.o' failed
make[2]: *** [CMakeFiles/slopy.dir/src/slop.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/slopy.dir/all' failed
make[1]: *** [CMakeFiles/slopy.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I've previously ran cmake -DCMAKE_INSTALL_PREFIX="/usr" ./ that got me the
following output:

CMake Warning at CMakeLists.txt:112 (find_package):
  By not providing "FindICU.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ICU", but
  CMake did not find one.

  Could not find a package configuration file provided by "ICU" with any of
  the following names:

    ICUConfig.cmake
    icu-config.cmake

  Add the installation prefix of "ICU" to CMAKE_PREFIX_PATH or set "ICU_DIR"
  to a directory containing one of the above files.  If "ICU" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/tim/local/src/slop

I'm a bit confused about the ICU files things. I don't really understand
how to fix it, nor if it's related at all.

Any help appreciated,

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/naelstrof/slop/issues/88>, or mute the thread

**Comment by AloisMahdal** [comment]
He mentioned he uses Ubuntu.

@pixelastic according to [debian package search][1], `EGL/egl.h` is in `libegl1-mesa-dev`, so `apt-get install libegl1-mesa-dev` should help.

Or you could skip re-building and use Debian package; reasonably recent version is in Sid.  I don't know how "far away" uis Ubuntu 16.04 from Sid, thougg, but you could give it a try:

 1. Download .deb file for your architecture from [package page][2],

 2. run `sudo dpkg -i /path/to/the.deb`; this will probably fail due to missing deps, leaving
    slop "half-installed"

 3. run `sudo apt-get -f install` to install dependencies and finish slop setup.

    If this fails, you're out of luck and you should run `dpkg -r slop` to clean up.

  [1]: https://packages.debian.org/search?searchon=contents&keywords=EGL%2Fegl.h
  [2]: https://packages.debian.org/sid/slop

**Comment by naelstrof** [comment]
Ah sorry, I'm busy and on a phone.
Thanks for clearing things up Alois.

**Comment by pixelastic** [comment]
Thanks for the inputs. I've tried downloading the `.deb` file, and followed your instructions.

``$ sudo dpkg -i slop_7.3.49-1_amd64.deb
Selecting previously unselected package slop.
(Reading database ... 226342 files and directories currently installed.)
Preparing to unpack slop_7.3.49-1_amd64.deb ...
Unpacking slop (7.3.49-1) ...
dpkg: dependency problems prevent configuration of slop:
 slop depends on libglew2.0 (>= 1.12.0); however:
  Package libglew2.0 is not installed.
 slop depends on libicu57 (>= 57.1-1~); however:
  Package libicu57 is not installed.

dpkg: error processing package slop (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 slop
```
As you predicted, `slop` is half-installed. But when I try to install the missing dependencies:

```
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  slop
0 upgraded, 0 newly installed, 1 to remove and 96 not upgraded.
1 not fully installed or removed.
After this operation, 387 kB disk space will be freed.
(Reading database ... 226336 files and directories currently installed.)
Removing slop (7.3.49-1) ...
Processing triggers for man-db (2.7.5-1) ...
```
The command itself does not fails, but `which slop` is empty.

**Comment by AloisMahdal** [comment]
The attempt with installing .deb package shows that there are no suitable packages in your Ubuntu repos that would satisfy slop's dependencies. That is why the `apt-get -f install` decides to remove slop--it can't find better solution.

So I guess your only way is to compile slop for yourself.

By installing `libmesa-dev`, you have solved the missing `EGL/egl.h`.  Now the compile process moved on to next dependecy, `GL/glew.h`.  So it's all about figuring out (in which package) where the file is on your distro and installing that.

If you look closely on my post, I used Debian package search to figure out that `egl.h` is in package called `libmesa-dev`.  This assumes files are packaged in Ubuntu the same way as on Debian.  This is true for ~90% of files, but there's *apt-file* utility, which provides a more reliable way:

    sudo apt-get install apt-file
    apt-file update    # under normal user

    $ apt-file search GL/glew.h
    libglew-dev: /usr/include/GL/glew.h
    libglewmx-dev: /usr/include/GL/glew.h
    libogre-1.9-dev: /usr/include/OGRE/RenderSystems/GL/GL/glew.h
    nvidia-cg-doc: /usr/share/doc/nvidia-cg-doc/examples/OpenGL/glew/include/GL/glew.h
    psychtoolbox-3-common: /usr/share/psychtoolbox-3/PsychOpenGL/MOGL/source/GL/glew.h
    $ 

The result shows multiple packages, but we normally want the "shortest" one, ie. one where the path is directly under `/usr/iunclude`.  So your next package to install is `libglew-dev`.  Once you do, the compile process will probably halt the same way on another missing file and then another; you can repeat the process as many times needed until it succeeds.

That's unless the compiling fails on something else than just missing dependency.  It might eventually fail because a library packaged in your distro is really not "good enough" for slop.  In that case, you're probably out of luck.

**Comment by pixelastic** [comment]
Thanks a lot for the detailed explanation. I'll dig into it further and see
if I can get all the dependencies to pass.

I had an earlier version of slop to work on the same distribution (but
different laptop) earlier this year. If needed, I'll fallback to the old
version.

Thanks for your time educating me on all of this, I appreciate it.

**Comment by pixelastic** [comment]
`libegl1-mesa-dev` and `libglew-dev` were actually the only dependencies missing for me. Thanks for your time and patience, I've got slop correctly installed now :)
